import 'css/global.css';
import { Roboto_Condensed } from 'next/font/google';

const roboto = Roboto_Condensed({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  style: ['normal'],
});

export const metadata = {
  title: 'Cafe Maddy Cab',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
